// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace CleanWebApiTemplate.Infrastructure.CompiledModels
{
    public partial class SqlDbContextModel
    {
        private SqlDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("c76391b1-b5ad-4237-87e0-f988170f26f2"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var todoEntity = TodoEntityEntityType.Create(this);

            TodoEntityEntityType.CreateAnnotations(todoEntity);

            AddAnnotation("ProductVersion", "10.0.1");
        }
    }
}
