// <auto-generated />
using CleanWebApiTemplate.Infrastructure.CompiledModels;
using CleanWebApiTemplate.Infrastructure.Context;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(SqlDbContext), typeof(SqlDbContextModel))]
